benefica/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'benefica.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r'^payments/', include('payments.urls', namespace='payments')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^carts/', include('carts.urls', namespace='carts')),
    url(r'^billing/', include('billing.urls', namespace='billing')),
    url(r'^$', include('main.urls', namespace='main')),
    url(r'^admin/', include(admin.site.urls)),
)

main/urls.py
from django.conf.urls import patterns, url
from main import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
)

payments/urls.py
from django.conf.urls import url, patterns

from payments import views

urlpatterns = patterns('',
    url('^$', views.PaymentView.as_view(), name='index'),
)

payments/models.py
from django.db import models
from django import forms


class PaymentForm(forms.Form):
    first_name = forms.CharField(label='First Name')
  
    class Meta:
        abstract = True


class Payment(models.Model):
    total = models.DecimalField(max_digits=14, decimal_places=2)

payments/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView

import stripe


stripe.api_key = "sk_test_w96KeQLCTh23810DSE2ykwIt"


class PaymentView(TemplateView):
    template_name = 'payments/index.html'
   
    def get_context_data(self, **kwargs):
        context = super(PaymentView, self).get_context_data(**kwargs)
        context['price'] = self.request.session['price']  
        return context
     
    def post(self, request, *args, **kwargs):
        token = request.POST.get("stripeToken")
        price = self.request.session['price']
        try:
            charge = stripe.Charge.create(
                # Stripe works in cents instead of dollars.
                # Multiply price by 100 to convert to cents
                amount = int(float(price)*100),

                currency="usd",
                card = token,
                description="For Donation"
            )
            return HttpResponse("You were succesfully charged $" + price)
        except stripe.CardError, e:
            return HttpResponse("its broken")

payments/templates/payments/index.html
{% extends 'wrapper.html' %}

{% block head_tags %}
{{ block.super }}
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">Stripe.setPublishableKey('pk_test_p0c5Rc1Mjs0cY9GfbzMhieLi');</script>
{% endblock head_tags %}

{% block content %}

<div class="container">
<form action="{% url 'payments:index' %}" method="POST" id="payment-form">
  {% csrf_token %}
  <span class="payment-errors"></span>
<h3>Price: &#36;{{ price }} </h3>
  <div class="form-row">
    <label>
      <span>Card Number</span>
      <input type="text" size="20" data-stripe="number"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>CVC</span>
      <input type="text" size="4" data-stripe="cvc"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>Expiration (MM/YYYY)</span>
      <input type="text" size="2" data-stripe="exp-month"/>
    </label>
    <span> / </span>
    <input type="text" size="4" data-stripe="exp-year"/>
  </div>

  <button type="submit">Submit Payment</button>
</form>

<script>
jQuery(function($) {
  $('#payment-form').submit(function(event) {
    var $form = $(this);

    // Disable the submit button to prevent repeated clicks
    $form.find('button').prop('disabled', true);

    Stripe.card.createToken($form, stripeResponseHandler);

    // Prevent the form from submitting with the default action
    return false;
  });
});


function stripeResponseHandler(status, response) {
  var $form = $('#payment-form');

  if (response.error) {
    // Show the errors on the form
    $form.find('.payment-errors').text(response.error.message);
    $form.find('button').prop('disabled', false);
  } else {
    // response contains id and card, which contains additional card details
    var token = response.id;
    // Insert the token into the form so it gets submitted to the server
    $form.append($('<input type="hidden" name="stripeToken" />').val(token));
    // and submit
    $form.get(0).submit();
  }
};
</script>
</div>
{% endblock content %}