benefica/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'benefica.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r'^payments/', include('payments.urls', namespace='payments')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^carts/', include('carts.urls', namespace='carts')),
    url(r'^billing/', include('billing.urls', namespace='billing')),
    url(r'^$', include('main.urls', namespace='main')),
    url(r'^admin/', include(admin.site.urls)),
)

main/urls.py
from django.conf.urls import patterns, url
from main import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
)

products/urls.py
from django.conf.urls import url, patterns
from products import views

urlpatterns = patterns('',
    url(r'^add', views.ProductCreateView.as_view(), name='add'),
    url(r'^list', views.ProductListView.as_view(), name='list')
) 

products/models.py
from django.conf import settings
from django.db import models
from django.forms import ModelForm


class Product(models.Model):
    title = models.CharField(max_length=60)
    description = models.CharField(max_length=255)
    image = models.ImageField(upload_to='products')
    price = models.DecimalField(max_digits=14, decimal_places=2)
    qty = models.PositiveIntegerField()

products/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView
from django.contrib.auth.decorators import login_required

from products.models import Product
from customusers.models import User

# Create your views here.
@login_required(redirect_field_name=None)
def add(request):
    if request.method == 'GET':
	form = ProductForm 
	return render(request, 'products/add.html', {'form': form})
    
    elif request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)

        if form.is_valid():
            product = form.save(commit=False)
            product.user = User.objects.get(pk=request.user.id)
            product.save()
            return redirect('main:index') 
        else:
            return render(request, 'products/add.html', {'form': form})


class ProductCreateView(CreateView):
    model = Product
    fields = ['title', 'description', 'image', 'price']

    def form_valid(self, form):
        product = form.save(commit=False)
        product.user = User.objects.get(pk=self.request.user.id) 
        product = form.save()
        return redirect('profiles:index')


class ProductListView(ListView):  
    model = Product            

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        self.request.session['cart'] = []
        self.request.session.modified = True
        return context

products/templates/products/add.html
{% extends 'wrapper.html' %}
{% load bootstrap %}

{% block head_tags %}
<style>
form{
  width: 350px;
  background-color: hsl(150, 0%, 96%);
}
</style>
{% endblock %}

{% block content %}
<div class="container">
  <form method='POST' enctype="multipart/form-data">
    {% csrf_token %}
    {{ form | bootstrap }}
    <button type="submit" class="btn btn-primary">Donate!</button>
  </form>
</div>
{% endblock %}

products/templates/products/product_form.html
{% extends 'wrapper.html' %}
{% load bootstrap %}

{% block head_tags %}
<style>
form{
  width: 350px;
  background-color: hsl(150, 0%, 96%);
}
</style>
{% endblock %}

{% block content %}
<div class="container">
  <form method='POST' enctype="multipart/form-data">
    {% csrf_token %}
    {{ form | bootstrap }}
    <button type="submit" class="btn btn-primary">Donate!</button>
  </form>
</div>
{% endblock %}

products/templates/products/product_list.html
{% extends 'wrapper.html' %}

{% block head_tags %}
{{ block.super }}
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">Stripe.setPublishableKey('pk_test_p0c5Rc1Mjs0cY9GfbzMhieLi');</script>
{% endblock head_tags %}

{% block content %}
<div class="container">
  <h1>Product</h1>
  {% for product in product_list %}
  <div>
    <p>{{ product.description }}</p>
    <p>{{ product.user.user_handle }} </p>
    <p>{{ product.price }}</p>
    <img width="150px" height="180px" src="{{MEDIA_URL}}{{product.image}}"/>
    <button class="btn btn-primary cartbtn" data-product_id="{{ product.id }}">Add to Cart</button> 
  </div>
  {% endfor %}
</div>

<script>
$('.cartbtn').click(function(event){
  $.post(
     "{% url 'carts:index' %}", 
     { 
        product_id: $(this).data('product_id'), 
        csrfmiddlewaretoken: '{{ csrf_token }}' 
     },
     function(data){
        alert(data);
     }
  );

});
</script>

{% endblock content %}