account/urls.py
from django.conf.urls import patterns, url
from account import views

urlpatterns = patterns('',
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^signout/$', views.signout, name='signout'),
)

benefica/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'benefica.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r'^payments/', include('payments.urls', namespace='payments')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^carts/', include('carts.urls', namespace='carts')),
    url(r'^billing/', include('billing.urls', namespace='billing')),
    url(r'^$', include('main.urls', namespace='main')),
    url(r'^admin/', include(admin.site.urls)),
)

main/urls.py
from django.conf.urls import patterns, url
from main import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
)

main/views.py
from django.shortcuts import render, redirect

# Create your views here.
def index(request):
    return redirect('products:list')

main/templates/wrapper.html
{% load staticfiles %}
<!DOCTYPE html>
<head>
<title>{% block title %}Benefica{% endblock %}</title>
<meta charset="utf-8">
<meta name="robots" content="noindex">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'assets/js/docs.js' %}"></script>

<style>
body{
margin-top: 70px;
}
</style>

{% block head_tags %}
{% endblock %}
</head>

<body>
  <nav class="navbar navbar-default pull-right">
    <ul class="nav navbar-nav">
      <li><a href="{% url 'main:index' %}">Home</a></li>
      <li><a href="{% url 'account:signup' %}">Signup</a></li>
      <li><a href="{% url 'profiles:index' %}">Profile</a></li>
      <li><a href="#">Shop</a></li>
      <li><a href="{% url 'billing:index' %}">Checkout</a></li>
      <li><a href="{% url 'account:signin' %}">Login</a></li>
      <li><a href="{% url 'account:signout' %}">Log Out</a></li>
    </ul>
  </nav>

{% block content %}
{% endblock %}

</body>
</html>